<a href="https://colab.research.google.com/github/NiyazovIlia/PyTorch-1/blob/lesson-1/HW_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
test = torch.rand(3,4,5)
test

tensor([[[0.2805, 0.0575, 0.6059, 0.1768, 0.4512],
         [0.8222, 0.9186, 0.2394, 0.0995, 0.8782],
         [0.8276, 0.2435, 0.3745, 0.5776, 0.3072],
         [0.5514, 0.3609, 0.3575, 0.8166, 0.7214]],

        [[0.7238, 0.5975, 0.2145, 0.4305, 0.6677],
         [0.7485, 0.5125, 0.0426, 0.4392, 0.4594],
         [0.5064, 0.3507, 0.8959, 0.2777, 0.9992],
         [0.1569, 0.1787, 0.5246, 0.1625, 0.4745]],

        [[0.8217, 0.3745, 0.1945, 0.3897, 0.1187],
         [0.3792, 0.7673, 0.2138, 0.3852, 0.8196],
         [0.6064, 0.0336, 0.2705, 0.7848, 0.7111],
         [0.3507, 0.5225, 0.2444, 0.5405, 0.2898]]])

In [3]:
# 2. Выведите его форму (shape)
test.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6 X 10
test = test.reshape(6,10)
print(test.shape, test)

torch.Size([6, 10]) tensor([[0.2805, 0.0575, 0.6059, 0.1768, 0.4512, 0.8222, 0.9186, 0.2394, 0.0995,
         0.8782],
        [0.8276, 0.2435, 0.3745, 0.5776, 0.3072, 0.5514, 0.3609, 0.3575, 0.8166,
         0.7214],
        [0.7238, 0.5975, 0.2145, 0.4305, 0.6677, 0.7485, 0.5125, 0.0426, 0.4392,
         0.4594],
        [0.5064, 0.3507, 0.8959, 0.2777, 0.9992, 0.1569, 0.1787, 0.5246, 0.1625,
         0.4745],
        [0.8217, 0.3745, 0.1945, 0.3897, 0.1187, 0.3792, 0.7673, 0.2138, 0.3852,
         0.8196],
        [0.6064, 0.0336, 0.2705, 0.7848, 0.7111, 0.3507, 0.5225, 0.2444, 0.5405,
         0.2898]])


In [5]:
# 4. Создайте случайный IntTensor размера 10
v = torch.randint(10, size=(10,))

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
v = torch.randint(10, size=(10,))
test2 = test * v
test2

tensor([[0.5610, 0.3451, 0.0000, 0.1768, 1.3536, 4.9330, 6.4303, 1.1970, 0.3981,
         7.9038],
        [1.6552, 1.4611, 0.0000, 0.5776, 0.9216, 3.3084, 2.5260, 1.7873, 3.2664,
         6.4927],
        [1.4475, 3.5852, 0.0000, 0.4305, 2.0032, 4.4908, 3.5874, 0.2129, 1.7567,
         4.1348],
        [1.0127, 2.1044, 0.0000, 0.2777, 2.9975, 0.9411, 1.2510, 2.6228, 0.6499,
         4.2707],
        [1.6435, 2.2473, 0.0000, 0.3897, 0.3560, 2.2753, 5.3708, 1.0692, 1.5408,
         7.3760],
        [1.2129, 0.2019, 0.0000, 0.7848, 2.1332, 2.1045, 3.6573, 1.2221, 2.1618,
         2.6078]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
test3 = torch.matmul(test2, test2.T)
test3.reshape(6,6)

tensor([[132.0422,  90.1027,  83.6924,  55.2409, 108.2001,  60.6105],
        [ 90.1027,  79.4033,  66.6129,  48.4864,  82.4857,  47.1004],
        [ 83.6924,  66.6129,  72.4116,  43.2076,  74.2343,  44.5020],
        [ 55.2409,  48.4864,  43.2076,  42.5075,  51.7356,  30.5689],
        [108.2001,  82.4857,  74.2343,  51.7356,  99.9751,  51.8161],
        [ 60.6105,  47.1004,  44.5020,  30.5689,  51.8161,  37.4508]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)
y = x**3 + z - 75*t
y.backward()
print(x.grad, z.grad, t.grad)

tensor(3.) tensor(1.) tensor(-75.)


In [9]:
# 8. Создайте единичный тензор размера 5x6
ten = torch.ones(5,6)
print(ten.shape, ten)

torch.Size([5, 6]) tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [10]:
# 9. Переведите его в формат numpy
import numpy
num = ten.numpy()
num

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)